// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4UHnCeQ4DdzdgGhWgTvYMGs_bSx-VSvs',
    appId: '1:531113037200:web:043c80e620d0ea50b0f715',
    messagingSenderId: '531113037200',
    projectId: 'dmx-512',
    authDomain: 'dmx-512.firebaseapp.com',
    storageBucket: 'dmx-512.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhcbZNR9Y8l-YMB85LqYSS5KE6nHyi1Z8',
    appId: '1:531113037200:android:87e1bc1aca3bf0e7b0f715',
    messagingSenderId: '531113037200',
    projectId: 'dmx-512',
    storageBucket: 'dmx-512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX_QBFALhB3bzzJYWbwVYPGm4ngKzNWYE',
    appId: '1:531113037200:ios:6046fcdfba520947b0f715',
    messagingSenderId: '531113037200',
    projectId: 'dmx-512',
    storageBucket: 'dmx-512.appspot.com',
    iosClientId: '531113037200-ujc9h404dtnsr2pummh91ohd9ce3nbn3.apps.googleusercontent.com',
    iosBundleId: 'com.shvedi.dmx512',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX_QBFALhB3bzzJYWbwVYPGm4ngKzNWYE',
    appId: '1:531113037200:ios:026c9f863a684b99b0f715',
    messagingSenderId: '531113037200',
    projectId: 'dmx-512',
    storageBucket: 'dmx-512.appspot.com',
    iosClientId: '531113037200-506h465ucqpenecg9ruukc4c2290citn.apps.googleusercontent.com',
    iosBundleId: 'com.shvedi.dmx512.RunnerTests',
  );
}
